### ISSUE TITLE
Unable to import libraries in Google Colab

### ISSUE THREAD

**Issue by wanjoochun** [pablo-arantes/Cloud-Bind#1]
Dear Pablo,

I am Wanjoo from Korea. I found your github's making-it-rain and Cloud-Bind codes very useful to me. I could try making-it-rain notebooks in Google Colab.
However, I could not run the GNINA and GNINA+MD notebooks in Google Colab. I am unable to install libraries. Would you please take a look and make them run in Google Colab? 
I hope I could try your codes in my research.

Best,

wanjoo 

wchunknu@gmail.com

**Comment by pablo-arantes** [comment]
Hi @wanjoochun,

I'm updating the notebooks, I will let you know when it is done. 

Thank you.

Best,

Pablo

**Comment by wanjoochun** [comment]
Hi Pablo,

Thank you so much for responding to my request.
I look forward to the updated version of your work.

Thanks again for your reply.

Best,

Wanjoo

**Comment by pablo-arantes** [comment]
Hi @wanjoochun 

I've updated all the notebooks. Now we have a new notebook, where you can evaluate ligand pose stability using metadynamics (OpenBPMD). 

Please, let me know if you have any issues.

Thank you.

Pablo

**Comment by wanjoochun** [comment]
Hi Pablo,

I really appreciate your prompt update on your work. I will study your
notebooks and try to apply them to my work.
I have been doing MD simulations using Gromacs in a local Linux
environment. Your work opens a new window for me.

Thanks again for your response and help.

Best,

Wanjoo
